DIET = {
    "vegana": "vegana",
    "vegano": "vegana",
    "vegetariana": "vegetariana",
    "vegetariano": "vegetariana",
    "sin gluten": "sin gluten",
    "no gluten": "sin gluten",
    "no tolero el gluten": "sin gluten",
    "no como gluten": "sin gluten",
    "no como carne": "vegetariana",
    "no como pescado": "vegetariana",
    "no como marisco": "vegetariana",
    "sin carne": "vegetariana",
    "sin pescado": "vegetariana",
    "sin marisco": "vegetariana"
}

TYPE_FOOD = {
    "almuerzo": "almuerzo",
    "desayuno": "desayuno",
    "cena": "cena",
    "tapa": "tapa",
    "postre": "postre",
    "comida": "almuerzo",
    "comida principal": "almuerzo",
    "plato principal": "almuerzo",
    "aperitivo": "tapa",
    "comida ligera": "cena",
    "almorzar": "almuerzo",
    "cenar": "cena",
    "tapeo": "tapa",
    "dulce": "postre"
}

DIFFICULTY = {
    "fácil": "fácil",
    "facil": "fácil",
    "sencilla": "fácil",
    "sencillo": "fácil",
    "simple": "fácil",
    "para principiantes": "fácil",
    "principiante": "fácil",
    "difícil": "alta",
    "dificil": "alta",
    "alta": "alta",
    "complicada": "alta",
    "complicado": "alta",
    "elaborada": "alta",
    "elaborado": "alta",
    "avanzada": "alta",
    "avanzado": "alta",
    "media": "media",
    "intermedia": "media",
    "intermedio": "media",
    "normal": "media"
}

TIME = {
    "rápido": 30,
    "rapido": 30,
    "rápida": 30,
    "rapida": 30,
    "poco tiempo": 30,
    "express": 30,
    "en 30 minutos": 30,
    "menos de 30 minutos": 30,
    "en media hora": 30,
    "30 min": 30,
    "15 minutos": 15,
    "15 min": 15,
    "en 15 minutos": 15,
    "corta": 15,
    "corto": 15,
    "larga": 60,
    "largo": 60,
    "en 60 minutos": 60,
    "una hora": 60,
    "1 hora": 60,
    "menos de una hora": 60,
    "no tengo tiempo": 15,
    "poco tiempo": 15,
    "tiempo limitado": 15
}